theme = "bento"
languageCode = "en-us"
baseurl = "http://hedge-ops.com/"
title = "Michael Hedgpeth"

author = "Michael Hedgpeth"
copyright = "MIT"

[permalinks]
  posts = "/:slug/"

[taxonomies]
category = "categories"
tag = "tags"

# Better code higlighting
# via https://discourse.gohugo.io/t/pygmentscodefences-how-to-choose-themes/3842/3
pygmentsCodefences = true
pygmentsStyle = "vs"

# Integrations
googleAnalytics = "UA-51220820-1"
disqusShortname = "hedge-ops"

# Hightlight theme
[markup.highlight]
  style = "github"

# Allow HTML rendering inside markdown
[markup.goldmark.renderer]
  unsafe = true

[params]
  # Show intro in the home page (with headline and description)
  intro = true
  headline = "Michael Hedgpeth"
  description = "Blogging about operational excellence through automation and cultural change"

  # Copyright note in the footer
  copyright = "Copyright © 2020 Michael Hedgpeth"

  # Image in the homepage. You can setup a different image for social media
  cover = "images/feature-devops-project.jpg"
  ogImage = "images/michael.jpg"

  # Social media usernames
  github = "mhedgpeth"
  twitter = "michaelhedgpeth"
  linkedin = "https://linkedin.com/in/michael-hedgpeth"

  # Learn more about webmention 
  # https://sebastiandedeyne.com/adding-webmentions-to-my-blog/
  # webmention = ""
  # productionBaseUrl is need if you want to receive webmentions in local environment
  # productionBaseUrl = "https://yourwebsite.com"

  # Avatar (shown in the homepage)
  avatar = "images/michael.jpg"
  # Bio is shown in the end of posts
  authorBio = "Michael Hedgpeth"

# Items in the top menu
[menu]
  [[menu.main]]
      name = "About"
      url = "/about"
      weight = 1

  [[menu.main]]
      name = "Speaking"
      url = "/speaking"
      weight = 1

